# Generated by Django 4.2.4 on 2023-08-22 21:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("Fichas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ficha",
            name="keywords",
        ),
        migrations.AddField(
            model_name="ficha",
            name="keywords",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
