# Generated by Django 4.2.4 on 2023-09-05 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0001_initial"),
        ("Fichas", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ficha",
            unique_together={("student", "assignment")},
        ),
    ]
