# Generated by Django 4.2.4 on 2023-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="status",
            field=models.CharField(
                choices=[("Borrador", "Borrador"), ("Publicado", "Publicado")],
                default="Borrador",
                max_length=10,
            ),
        ),
    ]
