# Generated by Django 4.2.4 on 2023-09-10 18:54

import Fichas.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0002_fichaimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complementaryimage",
            name="ficha",
        ),
        migrations.DeleteModel(
            name="Keywords",
        ),
        migrations.AlterField(
            model_name="ficha",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=Fichas.models.upload_to
            ),
        ),
        migrations.DeleteModel(
            name="ComplementaryImage",
        ),
    ]
