# Generated by Django 4.2.4 on 2023-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0002_ficha_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ficha",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="fichas/images/"),
        ),
    ]
