# Generated by Django 4.2.4 on 2023-10-09 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0003_remove_complementaryimage_ficha_delete_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="time_window_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
