# Generated by Django 4.2.4 on 2023-10-10 00:07

import Fichas.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0004_alter_assignment_time_window_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="time_window_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="time_window_start",
            field=models.DateField(default=Fichas.models.get_default_start_date),
        ),
    ]
