# Generated by Django 4.2.4 on 2023-10-16 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0001_initial"),
        ("Fichas", "0005_alter_assignment_time_window_end_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("teacher", "ficha")},
        ),
    ]
