# Generated by Django 4.2.4 on 2023-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0006_alter_review_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="anexos",
            field=models.URLField(blank=True),
        ),
    ]
