# Generated by Django 4.2.4 on 2023-10-17 17:05

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Fichas", "0007_ficha_anexos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ficha",
            name="anexos",
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
