# Generated by Django 4.2.4 on 2023-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumno",
            options={"verbose_name": "Alumne", "verbose_name_plural": "Alumnes"},
        ),
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name": "Profesor", "verbose_name_plural": "Profesores"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del usuario",
                max_length=50,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Apellido del usuario",
                max_length=50,
                verbose_name="Apellido",
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="CustomUser",
        ),
    ]
