# Generated by Django 4.2.4 on 2023-08-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Correo electrónico del usuario",
                max_length=254,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
    ]
