# Generated by Django 4.2.4 on 2023-08-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["last_name", "first_name", "role"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "Perfil de alumno",
                "verbose_name_plural": "Perfiles de alumnos",
            },
        ),
        migrations.AlterModelOptions(
            name="teacherprofile",
            options={
                "verbose_name": "Perfil de profesor",
                "verbose_name_plural": "Perfiles de profesores",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha de nacimiento del usuario",
                null=True,
                verbose_name="Fecha de nacimiento",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="year",
            field=models.CharField(
                choices=[("3", "3"), ("4", "4")], default="3", max_length=1
            ),
        ),
    ]
