# Generated by Django 4.2.4 on 2023-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0002_alumno_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/perfiles/profile_pictures",
                upload_to="media/perfiles/profile_pictures",
            ),
        ),
    ]
