# Generated by Django 4.2.4 on 2023-08-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="year",
            field=models.CharField(
                choices=[("3", "Tercer Año"), ("4", "Cuarto Año")],
                default="3",
                max_length=1,
            ),
        ),
    ]
