# Generated by Django 4.2.4 on 2023-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0003_alter_alumno_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="avatar",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/perfiles/profile_pictures",
                upload_to="media/perfiles/profile_pictures",
            ),
        ),
    ]
