# Generated by Django 4.2.4 on 2023-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cuentas", "0004_remove_alumno_avatar_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/perfiles/profile_pictures/default.png",
                upload_to="media/perfiles/profile_pictures",
            ),
        ),
    ]
