# Generated by Django 4.2.4 on 2023-08-17 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfiles"},
        ),
    ]
