# Generated by Django 4.2.4 on 2023-08-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0002_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars'),
        ),
    ]
