# Generated by Django 4.2.4 on 2023-08-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='Alumno',
        ),
        migrations.AlterModelTable(
            name='profesor',
            table='Profesor',
        ),
    ]
