# Generated by Django 4.2.4 on 2023-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_customuser_options_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Usuarios/profile_pictures/default.png', upload_to='Usuarios/profile_pictures'),
        ),
    ]
